update public.seo_service_pages
set body_sections = case service_slug
when 'interior-detail' then $$[
  {"heading":"Interior Detailing That Matches What Sacramento Drivers Search For","content":"When drivers search for interior car detailing in Sacramento, they usually need more than a quick vacuum. They are looking for help with dust in vents and seams, crumbs in family vehicles, pet hair in carpet fibers, sweat and sunscreen on seats, sticky cupholders, cloudy interior glass, and leather or plastic surfaces dried out by Sacramento heat. Interior Detail Only is built for that intent: a focused cabin reset that brings professional attention to the areas you touch every day without requiring a full exterior package."},
  {"heading":"Why Choose Drippy Suds for Interior Detail Only","content":"Drippy Suds is mobile, so the service comes to your driveway, apartment lot, or office by appointment. The team focuses on professional-grade results, eco-friendly products, and careful interior work instead of a rushed tunnel-wash experience. If your vehicle also needs outside cleaning, Interior Detail Only connects naturally with Exterior Wash Only. If the whole car needs a full reset, the Drippy Diamond Package is the stronger fit."},
  {"heading":"Best Fit for This Service","content":"Book Interior Detail Only when the vehicle smells stale, the seats and carpets feel dirty, the dashboard and panels look dusty, or the glass and mirrors need a streak-free refresh. It is especially useful for Sacramento, Elk Grove, Folsom, and Roseville drivers who commute, transport kids or pets, or park outdoors where heat and dust make interiors age faster."},
  {"heading":"Book Interior Detailing","content":"If your main goal is a cleaner cabin, start with Interior Detail Only. If you want interior cleaning plus paint-safe exterior care, compare this page with the Drippy Diamond Package before booking. For long-term exterior protection after the interior is handled, Ceramic Coatings are the next service to review."}
]$$::jsonb
when 'exterior-wash' then $$[
  {"heading":"Exterior Wash Service for Real Sacramento Conditions","content":"Search intent for exterior car wash and mobile exterior detailing is usually simple: the vehicle looks dirty, the paint feels rough, the wheels are dusty, and the owner wants it handled without driving to a shop. Exterior Wash Only answers that need with focused outside cleaning for road film, pollen, brake dust, bug splatter, dust, and everyday buildup from Sacramento streets and Central Valley weather."},
  {"heading":"Why Choose Drippy Suds for Exterior Wash Only","content":"Drippy Suds brings the exterior wash to your location by appointment and uses a detail-focused process rather than a generic automated wash. The service is designed for drivers who care about the finish, wheels, trim, and glass but do not need interior work that day. If you do need cabin cleaning too, pair this intent with Interior Detail Only or choose the Drippy Diamond Package for a complete inside-and-out service."},
  {"heading":"When Exterior Wash Only Is the Right Choice","content":"Choose Exterior Wash Only when the car needs a clean, fresh appearance but does not yet need ceramic protection or a full detail. It is a practical maintenance service for Sacramento, Rancho Cordova, Natomas, Elk Grove, and Folsom vehicles exposed to freeway grime, wind-blown dust, tree debris, and direct sun."},
  {"heading":"Book Exterior Wash Service","content":"Book Exterior Wash Only when you want the outside handled now. If your paint needs longer-term gloss, hydrophobic behavior, and UV protection, review Ceramic Coatings next. If you want exterior service plus interior detail in one visit, the Drippy Diamond Package is the better match."}
]$$::jsonb
when 'drippy-diamond-package' then $$[
  {"heading":"Full Mobile Detail for Drivers Who Want Everything Handled","content":"People searching for a full mobile car detail in Sacramento usually want one appointment that addresses both the cabin and the exterior. The Drippy Diamond Package is built for that search intent. It combines detailed vacuuming, leather and plastic shine, streak-free windows and mirrors, door jamb cleaning, premium wash and wax car shampoo, professional hand washing, rim and tire cleaning, and high-gloss tire dressing."},
  {"heading":"Why Choose the Drippy Diamond Package","content":"This is the most complete service for drivers who do not want to choose between Interior Detail Only and Exterior Wash Only. Drippy Suds brings the work to your location and focuses on a showroom-style result with professional equipment, eco-friendly products, and careful presentation. It is a strong choice before selling a vehicle, after heavy family use, before an event, or when the car simply needs a reset."},
  {"heading":"Best Match for Sacramento-Area Vehicles","content":"The Drippy Diamond Package fits daily drivers, family SUVs, work vehicles, and commuter cars throughout Sacramento, Roseville, Elk Grove, Folsom, and Rancho Cordova. It targets the common local combination of dusty paint, dirty wheels, sun-worn trim, messy interiors, and glass that needs a streak-free finish."},
  {"heading":"Book the Full Detail","content":"Book the Drippy Diamond Package when you want the full inside-and-out service in one appointment. If you only need the cabin, use Interior Detail Only. If your vehicle is already clean but needs longer-term paint protection, review Ceramic Coatings before booking."}
]$$::jsonb
when 'ceramic-coatings' then $$[
  {"heading":"Ceramic Coating for Long-Term Paint Protection","content":"Search intent for ceramic coating in Sacramento is different from a basic wash. Drivers want to know whether the service protects paint, improves gloss, makes washing easier, and holds up against sun, heat, dust, bird droppings, tree sap, and water spots. Ceramic Coatings are the protection-focused service for that intent, with paint preparation followed by a nano-ceramic layer designed for hydrophobic behavior, UV resistance, chemical resistance, and long-lasting gloss."},
  {"heading":"Why Choose Drippy Suds for Ceramic Coatings","content":"Drippy Suds positions ceramic work as a professional-grade detailing service, not a quick add-on. The process starts with paint prep because coatings only perform well when the surface is properly cleaned and prepared. For drivers still deciding between services, Exterior Wash Only is for routine exterior maintenance, the Drippy Diamond Package is for full presentation, and Ceramic Coatings are for durable protection after the finish is ready."},
  {"heading":"Why Sacramento Vehicles Benefit","content":"Sacramento-area vehicles face intense UV exposure, Central Valley dust, hot parking lots, tree sap, brake dust, and seasonal road film. Ceramic Coatings are especially useful for vehicles parked outdoors in Sacramento, Folsom, Roseville, Elk Grove, Natomas, and Rancho Cordova because they help maintain gloss and make future cleaning easier."},
  {"heading":"Book Ceramic Coating","content":"Book Ceramic Coatings when your goal is longer-term paint protection rather than a one-time wash. If the vehicle needs a complete interior and exterior reset first, review the Drippy Diamond Package. If you only need basic outside cleaning before deciding on protection, start with Exterior Wash Only."}
]$$::jsonb
else body_sections end,
cta_text = case service_slug
when 'interior-detail' then 'Ready for a cleaner cabin? Book Interior Detail Only and let Drippy Suds bring the interior reset to your location.'
when 'exterior-wash' then 'Ready for a fresh exterior? Book Exterior Wash Only and get paint-safe mobile cleaning at your location.'
when 'drippy-diamond-package' then 'Ready for the full reset? Book the Drippy Diamond Package for complete inside-and-out mobile detailing.'
when 'ceramic-coatings' then 'Ready for longer-term gloss and protection? Book Ceramic Coatings and protect your finish from Sacramento conditions.'
else cta_text end,
updated_at = now()
where service_slug in ('interior-detail','exterior-wash','drippy-diamond-package','ceramic-coatings');